Repository ITZipProject/itzip_back, pull requests merged in 2024-12, with the labels that each got.

#184 🛠️ 리팩토링 : Scrap캐싱 적용
  src/main/java/darkoverload/itzip/feature/job/controller/JobInfoController.java
  src/main/java/darkoverload/itzip/feature/job/domain/ConnectJobInfo.java
  src/main/java/darkoverload/itzip/feature/job/domain/JobInfo.java
  src/main/java/darkoverload/itzip/feature/job/domain/JobInfoScrap.java
  src/main/java/darkoverload/itzip/feature/job/domain/job/JobInfo.java
  src/main/java/darkoverload/itzip/feature/job/domain/scrap/JobInfoScrap.java
  src/main/java/darkoverload/itzip/feature/job/domain/scrap/JobInfoScrapType.java
  src/main/java/darkoverload/itzip/feature/job/entity/JobInfoScrapEntity.java
  src/main/java/darkoverload/itzip/feature/job/repository/JobInfoRepository.java
  src/main/java/darkoverload/itzip/feature/job/repository/JobInfoScrapRepository.java
  src/main/java/darkoverload/itzip/feature/job/repository/custom/CustomJobInfoScrapRepository.java
  src/main/java/darkoverload/itzip/feature/job/repository/custom/jobinfo/CustomJobInfoRepository.java
  src/main/java/darkoverload/itzip/feature/job/repository/custom/jobinfo/CustomJobInfoRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/job/repository/custom/scrap/CustomJobInfoScrapRepository.java
  src/main/java/darkoverload/itzip/feature/job/repository/custom/scrap/CustomJobInfoScrapRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/job/repository/redis/JobInfoScrapRedisCommandRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/job/repository/redis/JobInfoScrapRedisReadRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/job/scheduler/JobInfoScheduler.java
  src/main/java/darkoverload/itzip/feature/job/scheduler/JobInfoScrapScheduler.java
  src/main/java/darkoverload/itzip/feature/job/service/JobInfoScrapRedisService.java
  src/main/java/darkoverload/itzip/feature/job/service/JobInfoScrapRedisServiceImpl.java
  src/main/java/darkoverload/itzip/feature/job/service/JobInfoService.java
  src/main/java/darkoverload/itzip/feature/job/service/JobInfoServiceImpl.java
  src/main/java/darkoverload/itzip/feature/job/service/connect/JobInfoConnectService.java
  src/main/java/darkoverload/itzip/feature/job/service/connect/JobInfoConnectServiceImpl.java
  src/main/java/darkoverload/itzip/feature/job/service/port/JobInfoScrapRedisCommandRepository.java
  src/main/java/darkoverload/itzip/feature/job/service/port/JobInfoScrapRedisReadRepository.java
  src/main/java/darkoverload/itzip/feature/job/service/port/JobInfoScrapRepository.java
  src/main/java/darkoverload/itzip/feature/job/util/JobInfoJsonUtil.java
  src/main/java/darkoverload/itzip/feature/user/entity/UserEntity.java
  src/main/java/darkoverload/itzip/feature/user/service/UserService.java
  src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
  src/main/java/darkoverload/itzip/global/config/redis/RedisConfig.java
  src/main/java/darkoverload/itzip/global/config/scheduler/SchedulerConfig.java
  src/test/java/darkoverload/itzip/feature/job/domain/JobInfoScrapTest.java
  src/test/java/darkoverload/itzip/feature/job/domain/JobInfoTest.java
  src/test/java/darkoverload/itzip/feature/job/repository/JobInfoScrapRedisRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/job/repository/JobInfoScrapRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/job/service/JobInfoServiceImplTest.java
  src/test/java/darkoverload/itzip/feature/job/service/connect/JobInfoConnectServiceTest.java
  src/test/java/darkoverload/itzip/feature/job/service/connect/JobInfoScheduleTest.java
  src/test/java/darkoverload/itzip/feature/job/util/JobInfoJsonUtilTest.java
Labels: 🛠️ Refactor

#185 🚑 긴급 수정 : 코드 컨벤션에 맞게 괄호 뒤 공백 추가
  src/main/java/darkoverload/itzip/feature/techinfo/controller/post/response/PostCommentResponse.java
  src/main/java/darkoverload/itzip/feature/techinfo/controller/post/response/PostPreviewResponse.java
  src/main/java/darkoverload/itzip/feature/techinfo/domain/blog/Blog.java
  src/main/java/darkoverload/itzip/feature/techinfo/domain/blog/BlogDetails.java
  src/main/java/darkoverload/itzip/feature/techinfo/dto/post/WeeklyPostStats.java
  src/main/java/darkoverload/itzip/feature/techinfo/model/document/LikeDocument.java
  src/main/java/darkoverload/itzip/feature/techinfo/model/document/PostDocument.java
  src/main/java/darkoverload/itzip/feature/techinfo/repository/blog/BlogCommandRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/repository/blog/BlogReadRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/repository/blog/custom/CustomBlogCommandRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/repository/blog/custom/CustomBlogReadRepository.java
  src/main/java/darkoverload/itzip/feature/techinfo/repository/blog/custom/CustomBlogReadRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/repository/comment/custom/CustomCommentCommandRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/post/PostReadService.java
Labels: ❗️ HOTFIX

#187 🛠️ 리팩토링 : 채용정보 도메인 테스트 추가 및 구조 변경
  src/main/java/darkoverload/itzip/feature/job/domain/job/JobInfoAggregator.java
  src/main/java/darkoverload/itzip/feature/job/domain/job/JobInfoIds.java
  src/main/java/darkoverload/itzip/feature/job/domain/job/JobInfos.java
  src/main/java/darkoverload/itzip/feature/job/domain/scrap/JobInfoScrap.java
  src/main/java/darkoverload/itzip/feature/job/scheduler/JobInfoScheduler.java
  src/main/java/darkoverload/itzip/feature/job/scheduler/JobInfoScrapScheduler.java
  src/main/java/darkoverload/itzip/feature/job/service/JobInfoScrapRedisServiceImpl.java
  src/main/java/darkoverload/itzip/feature/job/service/connect/JobInfoConnectService.java
  src/main/java/darkoverload/itzip/feature/job/service/connect/JobInfoConnectServiceImpl.java
  src/test/java/darkoverload/itzip/feature/job/domain/JobInfoScrapTest.java
  src/test/java/darkoverload/itzip/feature/job/domain/job/JobInfoAggregatorTest.java
  src/test/java/darkoverload/itzip/feature/job/domain/job/JobInfoIdsTest.java
  src/test/java/darkoverload/itzip/feature/job/domain/job/JobInfoTest.java
  src/test/java/darkoverload/itzip/feature/job/mock/JobInfoMockData.java
  src/test/java/darkoverload/itzip/feature/job/service/connect/JobInfoConnectServiceTest.java
Labels: 🛠️ Refactor

#189 ✨ 새 기능 : 파일 업로드 기능 구현
  src/main/java/darkoverload/itzip/feature/image/controller/ImageController.java
  src/main/java/darkoverload/itzip/feature/image/service/CloudStorageService.java
  src/main/java/darkoverload/itzip/feature/image/service/StorageService.java
  src/main/java/darkoverload/itzip/feature/resume/controller/ResumeController.java
  src/main/java/darkoverload/itzip/feature/resume/controller/request/CreateResumeRequest.java
  src/main/java/darkoverload/itzip/feature/resume/domain/resume/Resume.java
  src/main/java/darkoverload/itzip/feature/resume/domain/resume/ResumeDetails.java
  src/main/java/darkoverload/itzip/feature/resume/dto/resume/ResumeDto.java
  src/main/java/darkoverload/itzip/feature/resume/entity/ResumeEntity.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/ResumeService.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/ResumeServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/util/holder/UUIDHolder.java
  src/main/java/darkoverload/itzip/feature/resume/util/holder/UUIDHolderImpl.java
  src/main/java/darkoverload/itzip/infra/bucket/domain/DocumentFile.java
  src/main/java/darkoverload/itzip/infra/bucket/domain/DocumentFiles.java
  src/main/java/darkoverload/itzip/infra/bucket/service/AWSService.java
  src/main/resources/application.yml
  src/test/java/darkoverload/itzip/feature/image/service/CloudStorageServiceTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/resume/ResumeTest.java
  src/test/java/darkoverload/itzip/feature/resume/repository/resume/ResumeReadRepositoryTest.java
Labels: ✨ Feat

#190 🚑 긴급 수정 : 이력서 테스트 코드 에러 수정
  src/test/java/darkoverload/itzip/feature/resume/domain/achievement/AchievementTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/achievement/AchievementsTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/activity/ActivitiesTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/career/CareersTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/education/EducationsTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/language/LanguageTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/language/LanguagesTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/myskill/MySkillTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/myskill/MySkillsTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/qualification/QualificationTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/qualification/QualificationsTest.java
  src/test/java/darkoverload/itzip/feature/resume/domain/resume/ResumeTest.java
Labels: 🐞 Fix

#191 🚑 긴급 수정 : Repository 이미지 로직 추가로 인한 에러발생 해결
  src/main/java/darkoverload/itzip/feature/resume/entity/AchievementEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/CareerEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/LanguageEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/MySkillEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/QualificationEntity.java
  src/main/java/darkoverload/itzip/feature/resume/repository/resume/ResumeRepositoryImpl.java
  src/test/java/darkoverload/itzip/feature/resume/repository/achievement/AchievementReadRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/resume/repository/activity/ActivityReadRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/resume/repository/career/CareerReadRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/resume/repository/education/EducationReadRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/resume/repository/language/LanguageReadReadRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/resume/repository/myskill/MySkillReadRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/resume/repository/qualification/QualificationRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/resume/repository/resume/ResumeReadRepositoryTest.java
  src/test/resources/sql/achievement/achievement-repository-data.sql
Labels: ❗️ HOTFIX

#196 ✨ 새 기능 : 이력서 삭제 추가 및 SwaggerUI 형식에 맞게 에러 어노테이션 수정
  src/main/java/darkoverload/itzip/feature/resume/controller/ResumeController.java
  src/main/java/darkoverload/itzip/feature/resume/repository/resume/ResumeRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/ResumeService.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/ResumeServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/port/resume/ResumeRepository.java
Labels: ✨ Feat

#198 🎨 코드의 형태 개선 : 불필요한 개행 삭제로 가독성과 일관성 개선
  src/main/java/darkoverload/itzip/feature/techinfo/controller/blog/request/BlogUpdateIntroRequest.java
  src/main/java/darkoverload/itzip/feature/techinfo/controller/post/request/PostCommentUpdateRequest.java
  src/main/java/darkoverload/itzip/feature/techinfo/domain/blog/BlogPostTimeline.java
  src/main/java/darkoverload/itzip/feature/techinfo/domain/comment/Comment.java
  src/main/java/darkoverload/itzip/feature/techinfo/domain/comment/CommentDetails.java
  src/main/java/darkoverload/itzip/feature/techinfo/domain/post/Post.java
  src/test/java/darkoverload/itzip/feature/techinfo/mock/PostMockData.java
Labels: 🛠️ Refactor

#200 ☔️ 테스트 추가 : 테스트 코드 및 도메인 객체 생성 로직 유닛 테스트 작성
  src/main/java/darkoverload/itzip/feature/techinfo/controller/post/request/PostCommentCreateRequest.java
  src/main/java/darkoverload/itzip/feature/techinfo/controller/post/request/PostCreateRequest.java
  src/main/java/darkoverload/itzip/feature/techinfo/controller/post/response/PostCommentResponse.java
  src/main/java/darkoverload/itzip/feature/techinfo/controller/post/response/PostPreviewResponse.java
  src/main/java/darkoverload/itzip/feature/techinfo/domain/blog/BlogDetails.java
  src/main/java/darkoverload/itzip/feature/techinfo/domain/post/PostDetails.java
  src/main/java/darkoverload/itzip/feature/techinfo/domain/post/PostInfo.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/post/PostReadService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/post/PostReadServiceImpl.java
  src/test/java/darkoverload/itzip/feature/techinfo/domain/blog/BlogDetailsTest.java
  src/test/java/darkoverload/itzip/feature/techinfo/domain/blog/BlogPostTimelineTest.java
  src/test/java/darkoverload/itzip/feature/techinfo/domain/blog/BlogTest.java
  src/test/java/darkoverload/itzip/feature/techinfo/domain/comment/CommentDetailsTest.java
  src/test/java/darkoverload/itzip/feature/techinfo/domain/comment/CommentTest.java
  src/test/java/darkoverload/itzip/feature/techinfo/domain/like/LikeTest.java
  src/test/java/darkoverload/itzip/feature/techinfo/domain/post/PostDetailsTest.java
  src/test/java/darkoverload/itzip/feature/techinfo/domain/post/PostInfoTest.java
  src/test/java/darkoverload/itzip/feature/techinfo/domain/post/PostTest.java
  src/test/java/darkoverload/itzip/feature/techinfo/domain/scrap/ScrapTest.java
Labels: ☔️ Test

#201 🛠️ 리팩토링: 채용공고 불필요한 컬럼 삭제
  src/main/java/darkoverload/itzip/feature/job/domain/job/JobInfo.java
  src/main/java/darkoverload/itzip/feature/job/domain/job/JobInfos.java
  src/main/java/darkoverload/itzip/feature/job/repository/JobInfoJpaRepository.java
  src/main/java/darkoverload/itzip/feature/job/repository/connect/JobInfoConnectJdbcRepository.java
  src/main/java/darkoverload/itzip/feature/job/repository/connect/JobInfoConnectRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/job/repository/redis/JobInfoScrapRedisCommandRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/job/repository/redis/JobInfoScrapRedisReadRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/job/scheduler/JobInfoScheduler.java
  src/main/java/darkoverload/itzip/feature/job/service/JobInfoScrapRedisServiceImpl.java
  src/main/java/darkoverload/itzip/feature/job/service/JobInfoServiceImpl.java
  src/main/java/darkoverload/itzip/feature/job/service/connect/JobInfoConnectService.java
  src/main/java/darkoverload/itzip/feature/job/service/connect/JobInfoConnectServiceImpl.java
  src/main/java/darkoverload/itzip/feature/job/service/connect/port/JobInfoConnectRepository.java
  src/main/java/darkoverload/itzip/feature/job/service/port/JobInfoRepository.java
  src/main/java/darkoverload/itzip/feature/job/service/port/redis/JobInfoScrapRedisCommandRepository.java
  src/main/java/darkoverload/itzip/feature/job/service/port/redis/JobInfoScrapRedisReadRepository.java
  src/main/java/darkoverload/itzip/feature/job/service/port/scrap/JobInfoScrapRepository.java
  src/main/java/darkoverload/itzip/feature/job/util/JobInfoJsonUtil.java
  src/test/java/darkoverload/itzip/feature/job/domain/JobInfoScrapTest.java
  src/test/java/darkoverload/itzip/feature/job/domain/job/JobInfoAggregatorTest.java
  src/test/java/darkoverload/itzip/feature/job/domain/job/JobInfoTest.java
  src/test/java/darkoverload/itzip/feature/job/mock/JobInfoMockData.java
  src/test/java/darkoverload/itzip/feature/job/repository/JobInfoJdbcRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/job/repository/JobInfoJpaRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/job/repository/JobInfoScrapRedisRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/job/service/connect/JobInfoScheduleTest.java
  src/test/java/darkoverload/itzip/feature/job/util/JobInfoJsonUtilTest.java
  src/test/resources/sql/jobinfo/delete-jobinfo-data.sql
  src/test/resources/sql/jobinfo/jobinfo-repository-data.sql
  src/test/resources/sql/jobinfo/scrap/infoscrap-repository-date.sql
Labels: 🛠️ Refactor
