Repository ITZipProject/itzip_back, pull requests merged in 2024-10, with the labels that each got.

#146 🐛 오류 수정 - 회원가입 비즈니스 로직 중 누락된 로직 추가
  src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
  src/main/java/darkoverload/itzip/feature/user/service/VerificationService.java
  src/main/java/darkoverload/itzip/feature/user/service/VerificationServiceImpl.java
Labels: 🐞 Fix

#147 🛠️ 리팩토링 : 회원 관련 기능 ResponseEntity 응답 문자열 리턴으로 변경
  src/main/java/darkoverload/itzip/feature/user/controller/MypageController.java
  src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
  src/main/java/darkoverload/itzip/feature/user/service/MypageService.java
  src/main/java/darkoverload/itzip/feature/user/service/MypageServiceImpl.java
  src/main/java/darkoverload/itzip/feature/user/service/UserService.java
  src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
Labels: 🛠️ Refactor

#152 🛠️ 리팩토링 : 회원 기능 파라미터 validation 예외처리 방식 변경 #109
  src/main/java/darkoverload/itzip/feature/user/controller/MypageController.java
  src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/ChangePasswordRequest.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/UserJoinRequest.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/UserLoginRequest.java
  src/main/java/darkoverload/itzip/feature/user/service/MypageService.java
  src/main/java/darkoverload/itzip/feature/user/service/MypageServiceImpl.java
  src/main/java/darkoverload/itzip/feature/user/service/UserService.java
  src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
  src/main/java/darkoverload/itzip/global/config/response/handler/GlobalExceptionHandler.java
Labels: 🛠️ Refactor

#155 ✅ 테스트 추가 : 알고리즘 테스트 코드 구현
  src/test/java/darkoverload/itzip/feature/algorithm/service/problem/FindProblemsByTagAndUserServiceTest.java
  src/test/java/darkoverload/itzip/feature/algorithm/service/problem/FindProblemsByUserServiceTest.java
  src/test/java/darkoverload/itzip/feature/algorithm/service/problem/SaveProblemsServiceTest.java
  src/test/java/darkoverload/itzip/feature/algorithm/service/tag/FindAllTagsServiceImplTest.java
  src/test/java/darkoverload/itzip/feature/algorithm/service/tag/SaveTagsServiceTest.java
  src/test/java/darkoverload/itzip/feature/algorithm/service/user/FindUserSolvedProfileServiceImplTest.java
  src/test/java/darkoverload/itzip/feature/algorithm/service/user/SaveUserSolvedProfileServiceImplTest.java
  src/test/java/darkoverload/itzip/feature/algorithm/service/user/UpdateUserSolvedProfileAndProblemServiceImplTest.java
Labels: ☔️ Test

#159 🛠️ 리팩토링: JWT 인증 방식 쿠키 -> 헤더로 변경
  src/main/java/darkoverload/itzip/feature/jwt/filter/TokenAuthenticationFilter.java
  src/main/java/darkoverload/itzip/feature/jwt/util/JwtTokenizer.java
  src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/RefreshAccessTokenRequest.java
  src/main/java/darkoverload/itzip/feature/user/service/UserService.java
  src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
  src/main/java/darkoverload/itzip/feature/user/util/CookieUtils.java
  src/main/java/darkoverload/itzip/global/config/response/exception/CustomErrorController.java
  src/main/java/darkoverload/itzip/global/config/swagger/SwaggerConfig.java
  src/main/resources/static/swagger-ui/index.html
Labels: 🛠️ Refactor

#161 ♻️ 코드 리팩토링 : 기술 정보 블로그 서비스 퍼사드 패턴 적용 및 하위 서비스 기능 구현
  src/main/java/darkoverload/itzip/feature/techinfo/controller/blog/TechInfoBlogController.java
  src/main/java/darkoverload/itzip/feature/techinfo/controller/blog/request/UpdateBlogIntroRequest.java
  src/main/java/darkoverload/itzip/feature/techinfo/controller/blog/response/BlogDetailsResponse.java
  src/main/java/darkoverload/itzip/feature/techinfo/controller/blog/response/BlogRecentPostsResponse.java
  src/main/java/darkoverload/itzip/feature/techinfo/controller/blog/response/BlogSummaryResponse.java
  src/main/java/darkoverload/itzip/feature/techinfo/controller/post/TechInfoPostController.java
  src/main/java/darkoverload/itzip/feature/techinfo/domain/Blog.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/BlogFacade.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/BlogFacadeImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/BlogService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/create/CreateBlogService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/create/CreateBlogServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/find/FindBlogDetailsService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/find/FindBlogDetailsServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/find/FindBlogRecentPostsService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/find/FindBlogRecentPostsServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/find/FindBlogService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/find/FindBlogServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/find/FindBlogSummaryService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/find/FindBlogSummaryServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/impl/BlogServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/update/UpdateBlogDisableService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/update/UpdateBlogDisableServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/update/UpdateBlogIntroService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/update/UpdateBlogIntroServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/post/PostService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/post/impl/PostBlogPreviewServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/post/impl/PostPreviewServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/post/impl/PostServiceImpl.java
Labels: 🛠️ Refactor

#163 🛠️ 리팩토링 : 이력서 기능 어댑터 패턴으로 리팩토링
  src/main/java/darkoverload/itzip/feature/job/controller/JobInfoController.java
  src/main/java/darkoverload/itzip/feature/job/repository/custom/CustomJobInfoRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/resume/controller/ResumeController.java
  src/main/java/darkoverload/itzip/feature/resume/controller/request/CreateResumeRequest.java
  src/main/java/darkoverload/itzip/feature/resume/controller/request/UpdateResumeRequest.java
  src/main/java/darkoverload/itzip/feature/resume/domain/achievement/Achievements.java
  src/main/java/darkoverload/itzip/feature/resume/domain/activity/Activities.java
  src/main/java/darkoverload/itzip/feature/resume/domain/career/Careers.java
  src/main/java/darkoverload/itzip/feature/resume/domain/education/Educations.java
  src/main/java/darkoverload/itzip/feature/resume/domain/language/Languages.java
  src/main/java/darkoverload/itzip/feature/resume/domain/myskill/MySkills.java
  src/main/java/darkoverload/itzip/feature/resume/domain/qualification/Qualifications.java
  src/main/java/darkoverload/itzip/feature/resume/domain/resume/Resume.java
  src/main/java/darkoverload/itzip/feature/resume/dto/achievement/AchievementDto.java
  src/main/java/darkoverload/itzip/feature/resume/dto/qualification/QualificationDto.java
  src/main/java/darkoverload/itzip/feature/resume/repository/achievement/AchievementJpaRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/achievement/AchievementRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/achievement/AchievementRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/resume/repository/activity/ActivityJpaRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/activity/ActivityRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/activity/ActivityRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/resume/repository/career/CareerJpaRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/career/CareerRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/career/CareerRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/resume/repository/education/EducationJpaRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/education/EducationRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/education/EducationRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/resume/repository/language/LanguageJpaRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/language/LanguageRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/language/LanguageRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/resume/repository/myskill/MySkillJpaRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/myskill/MySkillRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/myskill/MySkillRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/resume/repository/qualification/QualificationJpaRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/qualification/QualificationRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/qualification/QualificationRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/resume/repository/resume/ResumeJpaRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/resume/ResumeRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/ResumeService.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/ResumeServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/port/AchievementRepository.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/port/ActivityRepository.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/port/CareerRepository.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/port/EducationRepository.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/port/LanguageRepository.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/port/MySkillRepository.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/port/QualificationRepository.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/port/ResumeRepository.java
  src/main/java/darkoverload/itzip/feature/resume/util/ResumeValidatorCheck.java
  src/test/java/darkoverload/itzip/feature/job/repository/JobInfoScrapRepositoryTest.java
  src/test/java/darkoverload/itzip/feature/resume/service/ResumeServiceTest.java
Labels: 🛠️ Refactor

#165 🎨 코드의 구조 개선 : CQRS 패턴 미흡으로 인한 구조 조정
  src/main/java/darkoverload/itzip/feature/techinfo/controller/blog/TechInfoBlogController.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/BlogFacade.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/BlogFacadeImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/command/BlogCreateService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/command/BlogCreateServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/command/BlogDisableService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/command/BlogDisableServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/command/BlogUpdateIntroService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/command/BlogUpdateIntroServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/facade/BlogFacade.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/facade/BlogFacadeImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/query/BlogReadDetailsService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/query/BlogReadDetailsServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/query/BlogReadRecentPostsService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/query/BlogReadRecentPostsServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/query/BlogReadService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/query/BlogReadServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/query/BlogReadSummaryService.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/blog/query/BlogReadSummaryServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/post/impl/PostBlogPreviewServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/post/impl/PostPreviewServiceImpl.java
  src/main/java/darkoverload/itzip/feature/techinfo/service/post/impl/PostServiceImpl.java
Labels: 📛 Rename

#168 ✨ 새 기능 : 문제 생성 및 수정 시간 추가
  src/main/java/darkoverload/itzip/feature/csQuiz/controller/response/QuizDetailResponse.java
  src/main/java/darkoverload/itzip/feature/csQuiz/entity/QuizDocument.java
  src/main/java/darkoverload/itzip/feature/csQuiz/service/sub/quizzes/FindQuizQuerytImpl.java
  src/main/java/darkoverload/itzip/feature/csQuiz/util/QuizMapper.java
  src/main/resources/sql/quiz/data/Data_quizzes.json
Labels: ✨ Feat
