Repository ITZipProject/itzip_back, pull requests merged in 2024-08, with the labels that each got.

#44 ✨ 새 기능 : 이력서 테스트코드 작성 및 기능 구현
  build.gradle
  src/main/java/darkoverload/itzip/ItzipApplication.java
  src/main/java/darkoverload/itzip/global/config/response/code/CommonExceptionCode.java
  src/main/java/darkoverload/itzip/global/config/response/handler/GlobalExceptionHandler.java
  src/main/java/darkoverload/itzip/school/code/EstType.java
  src/main/java/darkoverload/itzip/school/code/RegionType.java
  src/main/java/darkoverload/itzip/school/code/SchoolType.java
  src/main/java/darkoverload/itzip/school/domain/School.java
  src/main/java/darkoverload/itzip/school/domain/WebClientWrapper.java
  src/main/java/darkoverload/itzip/school/entity/SchoolEntity.java
  src/main/java/darkoverload/itzip/school/repository/CustomSchoolRepository.java
  src/main/java/darkoverload/itzip/school/repository/CustomSchoolRepositoryImpl.java
  src/main/java/darkoverload/itzip/school/repository/SchoolRepository.java
  src/main/java/darkoverload/itzip/school/scheduler/SchoolScheduler.java
  src/main/java/darkoverload/itzip/school/service/SchoolConnectService.java
  src/main/java/darkoverload/itzip/school/service/SchoolConnectServiceImpl.java
  src/main/java/darkoverload/itzip/school/util/SchoolJsonUtil.java
  src/main/resources/application.yml
  src/test/java/darkoverload/itzip/image/repository/ImageRepositoryTest.java
  src/test/java/darkoverload/itzip/image/service/CloudStorageServiceTest.java
  src/test/java/darkoverload/itzip/school/SchoolInsertConnect.java
  src/test/java/darkoverload/itzip/school/SchoolServiceTest.java
  src/test/java/darkoverload/itzip/school/SchoolWebClientTest.java
  src/test/java/darkoverload/itzip/school/repository/SchoolRepositoryTest.java
  src/test/resources/application-test.yml
  src/test/resources/sql/image/delete-image-data.sql
  src/test/resources/sql/image/image-repository-data.sql
  src/test/resources/sql/school/delete-school-data.sql
  src/test/resources/sql/school/school-repository-data.sql
Labels: ✨ Feat

#51 🐛 버그 수정 : swagger 에러코드가 같아도 다른 에러로 swagger에 적히도록 수정
  src/main/java/darkoverload/itzip/global/config/swagger/SwaggerConfig.java
Labels: 🐞 Fix

#50 💡 Docs : 주석 추가 완료
  src/main/java/darkoverload/itzip/feature/school/code/EstType.java
  src/main/java/darkoverload/itzip/feature/school/code/RegionType.java
  src/main/java/darkoverload/itzip/feature/school/code/SchoolType.java
  src/main/java/darkoverload/itzip/feature/school/domain/School.java
  src/main/java/darkoverload/itzip/feature/school/scheduler/SchoolScheduler.java
  src/main/java/darkoverload/itzip/feature/school/service/SchoolConnectServiceImpl.java
  src/main/java/darkoverload/itzip/feature/school/util/SchoolJsonUtil.java
Labels: 📖 Docs

#54 ✨ 새기능 : 학교 정보 API 조회 코드 추가
  src/main/java/darkoverload/itzip/feature/school/controller/SchoolController.java
  src/main/java/darkoverload/itzip/feature/school/controller/response/SearchResponse.java
  src/main/java/darkoverload/itzip/feature/school/repository/CustomSchoolRepository.java
  src/main/java/darkoverload/itzip/feature/school/repository/CustomSchoolRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/school/repository/SchoolRepository.java
  src/main/java/darkoverload/itzip/feature/school/service/SchoolService.java
  src/main/java/darkoverload/itzip/feature/school/service/SchoolServiceImpl.java
  src/main/java/darkoverload/itzip/feature/school/service/connect/SchoolConnectService.java
  src/main/java/darkoverload/itzip/feature/school/service/connect/SchoolConnectServiceImpl.java
  src/test/java/darkoverload/itzip/feature/school/repository/SchoolRepositoryTest.java
Labels: ✨ Feat

#57 🚑 긴급 수정 - 로그인 시 token 데이터가 갱신되지 않는 오류 수정
  src/main/java/darkoverload/itzip/feature/jwt/domain/Token.java
  src/main/java/darkoverload/itzip/feature/jwt/repository/TokenRepository.java
  src/main/java/darkoverload/itzip/feature/jwt/service/TokenServiceImpl.java
Labels: ❗️ HOTFIX

#64 ✨ 새 기능 : 학교 정보 관련 자동완성 기능 추가
  build.gradle
  src/main/java/darkoverload/itzip/feature/school/controller/SchoolController.java
  src/main/java/darkoverload/itzip/feature/school/domain/School.java
  src/main/java/darkoverload/itzip/feature/school/entity/SchoolDocument.java
  src/main/java/darkoverload/itzip/feature/school/repository/CustomSchoolRepository.java
  src/main/java/darkoverload/itzip/feature/school/repository/CustomSchoolRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/school/repository/SchoolRepository.java
  src/main/java/darkoverload/itzip/feature/school/service/SchoolService.java
  src/main/java/darkoverload/itzip/feature/school/service/SchoolServiceImpl.java
  src/main/java/darkoverload/itzip/feature/school/service/connect/SchoolConnectServiceImpl.java
  src/main/java/darkoverload/itzip/feature/school/util/SchoolJsonUtil.java
  src/main/java/darkoverload/itzip/global/config/elastic/ElasticSearchConfig.java
  src/main/java/darkoverload/itzip/global/config/security/SecurityConfig.java
  src/main/resources/application-local.yml
  src/test/java/darkoverload/itzip/feature/school/SchoolInsertConnect.java
  src/test/java/darkoverload/itzip/feature/school/SchoolWebClientTest.java
  src/test/java/darkoverload/itzip/feature/school/repository/SchoolRepositoryTest.java
  src/test/resources/application-test.yml
Labels: ✨ Feat

#66 🛠️ 리팩토링 : 코드 구조 개선
  src/main/java/darkoverload/itzip/feature/school/repository/SchoolRepository.java
  src/main/java/darkoverload/itzip/feature/school/repository/custom/CustomSchoolRepository.java
  src/main/java/darkoverload/itzip/feature/school/repository/custom/CustomSchoolRepositoryImpl.java
  src/main/java/darkoverload/itzip/feature/school/service/SchoolServiceImpl.java
  src/test/java/darkoverload/itzip/feature/school/SchoolInsertConnect.java
Labels: 🛠️ Refactor

#69 ⚙️ 기본 설정 : nginx 리버스 프록시 설정에 따른 수정
  src/main/java/darkoverload/itzip/global/config/websupport/WebSuppportConfig.java
  src/main/resources/application.yml
Labels: ⚙️ Config

#74 🔀 병합 : MongoDB 다큐먼트 감사 필드 추가
  src/main/java/darkoverload/itzip/ItzipApplication.java
  src/main/java/darkoverload/itzip/global/entity/MongoAuditingFields.java
Labels: ✨ Feat

#77 💩 똥싼 코드 : Request 객체 snake case -> camel case로 변경
  src/main/java/darkoverload/itzip/feature/image/controller/request/ImageDeleteRequest.java
  src/main/java/darkoverload/itzip/feature/image/controller/request/ImageUploadRequest.java
Labels: 🛠️ Refactor

#79 🚑 긴급 수정 : MongoDB 감사 클래스 매핑 오류 수정
  src/main/java/darkoverload/itzip/ItzipApplication.java
  src/main/java/darkoverload/itzip/global/config/mongo/MongoConfig.java
Labels: ❗️ HOTFIX

#84 ✨ 새 기능 : 로그 시각화 모니터링 기능
  build.gradle
  src/main/resources/logback-spring.xml
Labels: ✨ Feat

#83 ✨ 새 기능 : 이력서 생성 기능 추가
  src/main/java/darkoverload/itzip/feature/image/controller/request/ImageDeleteRequest.java
  src/main/java/darkoverload/itzip/feature/image/controller/request/ImageUploadRequest.java
  src/main/java/darkoverload/itzip/feature/resume/code/PublicOnOff.java
  src/main/java/darkoverload/itzip/feature/resume/controller/ResumeController.java
  src/main/java/darkoverload/itzip/feature/resume/controller/request/CreateResumeRequest.java
  src/main/java/darkoverload/itzip/feature/resume/domain/achievement/CreateAchievement.java
  src/main/java/darkoverload/itzip/feature/resume/domain/activity/CreateActivity.java
  src/main/java/darkoverload/itzip/feature/resume/domain/career/CreateCareer.java
  src/main/java/darkoverload/itzip/feature/resume/domain/education/CreateEducation.java
  src/main/java/darkoverload/itzip/feature/resume/domain/language/CreateLanguage.java
  src/main/java/darkoverload/itzip/feature/resume/domain/myskill/CreateMySkill.java
  src/main/java/darkoverload/itzip/feature/resume/domain/qualification/CreateQualification.java
  src/main/java/darkoverload/itzip/feature/resume/domain/resume/CreateResume.java
  src/main/java/darkoverload/itzip/feature/resume/dto/achievement/CreateAchievementDto.java
  src/main/java/darkoverload/itzip/feature/resume/dto/activity/CreateActivityDto.java
  src/main/java/darkoverload/itzip/feature/resume/dto/career/CreateCareerDto.java
  src/main/java/darkoverload/itzip/feature/resume/dto/education/CreateEducationDto.java
  src/main/java/darkoverload/itzip/feature/resume/dto/language/CreateLanguageDto.java
  src/main/java/darkoverload/itzip/feature/resume/dto/myskill/CreateMySkillsDto.java
  src/main/java/darkoverload/itzip/feature/resume/dto/qualification/CreateQualificationDto.java
  src/main/java/darkoverload/itzip/feature/resume/dto/resume/CreateResumeDto.java
  src/main/java/darkoverload/itzip/feature/resume/entity/AchievementEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/ActivityEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/CareerEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/EducationEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/LanguageEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/MySkillEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/QualificationEntity.java
  src/main/java/darkoverload/itzip/feature/resume/entity/ResumeEntity.java
  src/main/java/darkoverload/itzip/feature/resume/repository/Activity/ActivityRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/achievement/AchievementRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/career/CareerRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/education/EducationRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/language/LanguageRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/myskill/MySkillRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/qualification/QualificationRepository.java
  src/main/java/darkoverload/itzip/feature/resume/repository/resume/ResumeRepository.java
  src/main/java/darkoverload/itzip/feature/resume/service/achievement/AchievementService.java
  src/main/java/darkoverload/itzip/feature/resume/service/achievement/AchievementServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/activity/ActivityService.java
  src/main/java/darkoverload/itzip/feature/resume/service/activity/ActivityServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/career/CareerService.java
  src/main/java/darkoverload/itzip/feature/resume/service/career/CareerServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/education/EducationService.java
  src/main/java/darkoverload/itzip/feature/resume/service/education/EducationServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/language/LanguageService.java
  src/main/java/darkoverload/itzip/feature/resume/service/language/LanguageServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/myskill/MySkillService.java
  src/main/java/darkoverload/itzip/feature/resume/service/myskill/MySkillServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/qualification/QualicationServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/service/qualification/QualificationService.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/ResumeService.java
  src/main/java/darkoverload/itzip/feature/resume/service/resume/ResumeServiceImpl.java
  src/main/java/darkoverload/itzip/feature/resume/util/ResumeConditional.java
  src/main/java/darkoverload/itzip/feature/resume/util/ResumeValidatorCheck.java
  src/main/java/darkoverload/itzip/feature/resume/util/StringListConverter.java
  src/main/java/darkoverload/itzip/global/config/response/code/CommonExceptionCode.java
  src/main/java/darkoverload/itzip/global/config/security/SecurityConfig.java
  src/main/resources/application.yml
Labels: ✨ Feat

#88 🛠️ 리팩토링 : 메일 발송 로직 리팩토링 #87
  src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/EmailSendRequest.java
  src/main/java/darkoverload/itzip/feature/user/service/EmailService.java
  src/main/java/darkoverload/itzip/feature/user/service/EmailServiceImpl.java
  src/main/java/darkoverload/itzip/feature/user/service/UserService.java
  src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
  src/main/resources/application-local.yml
  src/main/resources/templates/authMailForm.html
  src/test/java/darkoverload/itzip/feature/user/controller/UserControllerTest.java
  src/test/resources/application-test.yml
Labels: 🛠️ Refactor

#90 ✨ 새 기능: 이메일 중복 체크 기능
  src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/AuthEmailCheckRequest.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/AuthEmailSendRequest.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/DuplicateEmailRequest.java
  src/main/java/darkoverload/itzip/feature/user/service/UserService.java
  src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
  src/main/java/darkoverload/itzip/global/config/security/SecurityConfig.java
Labels: ✨ Feat

#91 🛠️ 리팩토링 : 회원 기능 전체 코드
  src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
  src/main/java/darkoverload/itzip/feature/user/service/UserService.java
  src/main/java/darkoverload/itzip/feature/user/service/UserServiceImpl.java
Labels: 🛠️ Refactor

#92 📖 문서 수정 : user swagger 최신화
  src/main/java/darkoverload/itzip/feature/user/controller/UserController.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/AuthEmailCheckRequest.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/UserJoinRequest.java
  src/main/java/darkoverload/itzip/feature/user/controller/request/UserLoginRequest.java
Labels: 📖 Docs

#95 🐛 버그 수정 : swagger 커스텀 어노테이션
  src/main/java/darkoverload/itzip/feature/algorithm/domain/Problem.java
  src/main/java/darkoverload/itzip/feature/algorithm/domain/ProblemTag.java
  src/main/java/darkoverload/itzip/feature/algorithm/domain/ProblemTagMapping.java
  src/main/java/darkoverload/itzip/feature/algorithm/domain/SolvedacUser.java
  src/main/java/darkoverload/itzip/feature/algorithm/domain/UserProblemMapping.java
  src/main/java/darkoverload/itzip/feature/algorithm/entity/ProblemEntity.java
  src/main/java/darkoverload/itzip/feature/algorithm/entity/ProblemTagEntity.java
  src/main/java/darkoverload/itzip/feature/algorithm/entity/ProblemTagMappingEntity.java
  src/main/java/darkoverload/itzip/feature/algorithm/entity/SolvedacUserEntity.java
  src/main/java/darkoverload/itzip/feature/algorithm/entity/UserProblemMappingEntity.java
  src/main/java/darkoverload/itzip/feature/algorithm/repository/problem/ProblemRepository.java
  src/main/java/darkoverload/itzip/feature/algorithm/repository/problem/custom/FindProblemByUser.java
  src/main/java/darkoverload/itzip/feature/algorithm/repository/problem/custom/FindProblemsByTagExcludingUserSolved.java
  src/main/java/darkoverload/itzip/feature/algorithm/repository/problem/custom/FindSolvedProlbmesByUserAndTag.java
  src/main/java/darkoverload/itzip/feature/csQuiz/controller/CsQuizController.java
  src/main/java/darkoverload/itzip/global/config/swagger/SwaggerConfig.java
  src/main/resources/sql/algorithm/algorithm.sql
Labels: 🐞 Fix
